import { useState } from "react";

interface Props {
  sql: string;
}

export default function SqlDisplay({ sql }: Props) {
  const [copied, setCopied] = useState(false);

  function copy() {
    navigator.clipboard.writeText(sql).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div className="rounded-xl border border-gray-700 overflow-hidden">
      {/* Header bar */}
      <div className="flex items-center justify-between bg-gray-800 px-4 py-2">
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono text-blue-400 font-semibold">SQL</span>
          <span className="text-xs text-gray-500">Generated by GPT-4o via RAG</span>
        </div>
        <button
          onClick={copy}
          className="text-xs px-2.5 py-1 rounded-md bg-gray-700 hover:bg-gray-600
                     text-gray-300 hover:text-white transition-colors"
        >
          {copied ? "✓ Copied" : "Copy"}
        </button>
      </div>

      {/* SQL code */}
      <pre className="bg-gray-900 px-5 py-4 overflow-x-auto text-sm font-mono
                      text-green-300 leading-relaxed whitespace-pre-wrap">
        {sql}
      </pre>
    </div>
  );
}
