import { useState } from "react";

interface FixEntry {
  attempt: number;
  error: string;
  sql: string;
}

interface Props {
  sql: string;
  attempts?: number;
  fixHistory?: FixEntry[];
}

export default function SqlDisplay({ sql, attempts = 1, fixHistory = [] }: Props) {
  const [copied, setCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const wasFixed = attempts > 1;

  function copy() {
    navigator.clipboard.writeText(sql).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div className="rounded-xl border border-gray-700 overflow-hidden">
      {/* Header bar */}
      <div className="flex items-center justify-between bg-gray-800 px-4 py-2 gap-3 flex-wrap">
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono text-blue-400 font-semibold">SQL</span>
          <span className="text-xs text-gray-500">Generated by GPT-4o via RAG</span>

          {/* Auto-fix badge */}
          {wasFixed && (
            <button
              onClick={() => setShowHistory((v) => !v)}
              className="flex items-center gap-1 text-xs px-2 py-0.5 rounded-full
                         bg-amber-900/60 border border-amber-700 text-amber-300
                         hover:bg-amber-800/60 transition-colors"
              title="SQL was auto-corrected — click to see fix history"
            >
              🔧 Auto-fixed in {attempts} attempt{attempts !== 1 ? "s" : ""}
              <span className="ml-0.5">{showHistory ? "▲" : "▼"}</span>
            </button>
          )}

          {/* Success badge for first-try */}
          {!wasFixed && (
            <span className="flex items-center gap-1 text-xs px-2 py-0.5 rounded-full
                             bg-emerald-900/40 border border-emerald-800 text-emerald-400">
              ✓ First try
            </span>
          )}
        </div>

        <button
          onClick={copy}
          className="text-xs px-2.5 py-1 rounded-md bg-gray-700 hover:bg-gray-600
                     text-gray-300 hover:text-white transition-colors"
        >
          {copied ? "✓ Copied" : "Copy"}
        </button>
      </div>

      {/* Fix history (collapsible, only shown when SQL was auto-corrected) */}
      {wasFixed && showHistory && (
        <div className="bg-amber-950/20 border-b border-amber-800/40 px-4 py-3 flex flex-col gap-3">
          <p className="text-xs font-semibold text-amber-400 uppercase tracking-wider">
            Auto-fix history — {fixHistory.length} failed attempt{fixHistory.length !== 1 ? "s" : ""} before success
          </p>
          {fixHistory.map((entry) => (
            <div key={entry.attempt} className="rounded-lg border border-amber-800/40 bg-gray-900 overflow-hidden">
              <div className="bg-amber-950/40 px-3 py-1.5 flex items-center gap-2">
                <span className="text-xs font-semibold text-amber-400">Attempt #{entry.attempt}</span>
                <span className="text-xs text-red-400 font-mono truncate flex-1">{entry.error}</span>
              </div>
              <pre className="px-3 py-2 text-xs font-mono text-gray-400 overflow-x-auto whitespace-pre-wrap">
                {entry.sql}
              </pre>
            </div>
          ))}
        </div>
      )}

      {/* Final (successful) SQL */}
      <pre className="bg-gray-900 px-5 py-4 overflow-x-auto text-sm font-mono
                      text-green-300 leading-relaxed whitespace-pre-wrap">
        {sql}
      </pre>
    </div>
  );
}
