"""
tests/generate_sql_report.py
-----------------------------
Reads the latest results JSON and produces tests/passing_sqls.md —
a human-readable catalogue of all 50 passing SQLs.

Usage:
    python tests/generate_sql_report.py
"""
import json
import os
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TESTS_DIR = os.path.join(BASE, "tests")
RESULTS_DIR = os.path.join(TESTS_DIR, "test_results")
OUT_PATH = os.path.join(TESTS_DIR, "passing_sqls.md")

# ── Load test questions ──────────────────────────────────────────────────────
test_cases = json.load(open(os.path.join(TESTS_DIR, "test_queries.json"), encoding="utf-8"))
q_map = {tc["id"]: tc for tc in test_cases}

# ── Find latest results JSON ─────────────────────────────────────────────────
json_files = sorted(
    [f for f in os.listdir(RESULTS_DIR) if f.startswith("results_") and f.endswith(".json")]
)
if not json_files:
    print("ERROR: No results JSON found in", RESULTS_DIR)
    sys.exit(1)

latest = os.path.join(RESULTS_DIR, json_files[-1])
print(f"Reading: {latest}")
results = json.load(open(latest, encoding="utf-8"))
results.sort(key=lambda r: r["id"])

# ── Build Markdown ───────────────────────────────────────────────────────────
lines = [
    "# MMS-GPT — 50 Passing SQLs Reference",
    "",
    "All 50 queries from the test suite, showing the final SQL generated by GPT-4o.",
    "Queries marked ⚠️ needed an auto-fix (2 attempts); all others passed on attempt 1.",
    "",
    f"*Source: `{json_files[-1]}`*",
    "",
    "---",
    "",
]

# Group table of contents by group
groups: dict = {}
for r in results:
    g = r.get("group", "")
    groups.setdefault(g, []).append(r["id"])

lines.append("## Table of Contents")
lines.append("")
for g, ids in groups.items():
    id_links = " · ".join(f"[Q{i}](#q{i})" for i in ids)
    lines.append(f"- **{g}**: {id_links}")
lines.append("")
lines.append("---")
lines.append("")

# Each query
for r in results:
    tid = r["id"]
    tc = q_map.get(tid, {})
    group = r.get("group", tc.get("group", ""))
    question = tc.get("question", r.get("question", ""))
    sql = r.get("sql", "").strip()
    att = r.get("attempts", 1)
    rows = r.get("row_count", 0)
    status = r.get("status", "?")
    att_note = f"  ⚠️ auto-fixed after {att} attempts" if att > 1 else ""

    lines.append(f"<a id='q{tid}'></a>")
    lines.append(f"## Q{tid} — `{group}`")
    lines.append("")
    lines.append(f"**Question:** {question}")
    lines.append(f"**Result:** {rows} rows | attempts={att}{att_note}")
    lines.append("")
    lines.append("```sql")
    lines.append(sql)
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")

output = "\n".join(lines)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write(output)

print(f"DONE: Written {len(results)} SQLs -> {OUT_PATH}")
