"""
api/main.py
-----------
FastAPI backend for MMS-GPT.

RAG pipeline per request:
  1. Embed the user's natural-language question (text-embedding-3-small)
  2. Retrieve top-K most similar schema chunks from planning.schema_embeddings (pgvector cosine)
  3. Build a GPT-4o prompt using ONLY those retrieved chunks (RAG, not CAG)
  4. GPT-4o returns a PostgreSQL query
  5. Validate the SQL (LIMIT 0 probe → no rows transferred, just schema check)
  6. If ≤ LARGE_RESULT_THRESHOLD rows exist → fetch all and return (client-side pagination)
     If  > LARGE_RESULT_THRESHOLD rows exist → return column info only; frontend paginates
        via the /api/paginate endpoint (server-side / Infinite Row Model)

Run:
    uvicorn api.main:app --reload --port 8000
"""

import os
import re
import psycopg2
import psycopg2.extras
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from openai import OpenAI
from dotenv import load_dotenv

from api.workflow.router import router as workflow_router
from api.workflow.engine import scheduler as wf_scheduler

# ── Config ──────────────────────────────────────────────────────────────────
load_dotenv(".env.local")
load_dotenv(".env")

DB_URL = os.environ["SUPABASE_DB_URL"]
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]

oai = OpenAI(api_key=OPENAI_API_KEY)

TOP_K = 7                      # schema chunks retrieved per question
MAX_ROWS = 5000                # hint given to the AI prompt for LIMIT
LARGE_RESULT_THRESHOLD = 5000  # rows above this → server-side pagination
MAX_SQL_RETRIES = 3            # max auto-fix attempts

# psycopg2 type OIDs that map to numeric types
NUMERIC_OIDS: set[int] = {
    20,   # int8  / bigint
    21,   # int2  / smallint
    23,   # int4  / integer
    700,  # float4 / real
    701,  # float8 / double precision
    1700, # numeric / decimal
    790,  # money
}

# SQL keywords that must never appear in a paginate request
_FORBIDDEN_SQL = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|GRANT|REVOKE)\b",
    re.IGNORECASE,
)

# ── FastAPI lifespan — start/stop APScheduler ────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    wf_scheduler.start()
    yield
    wf_scheduler.shutdown(wait=False)

# ── FastAPI app ──────────────────────────────────────────────────────────────
app = FastAPI(title="MMS-GPT API", lifespan=lifespan)
app.include_router(workflow_router)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten in production
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Request / Response models ────────────────────────────────────────────────
class QueryRequest(BaseModel):
    question: str


class ChunkDetail(BaseModel):
    key: str
    similarity: float
    excerpt: str
    full_text: str


class QueryResponse(BaseModel):
    sql: str
    columns: list[str]
    column_types: list[str]          # "numeric" | "text" per column
    rows: list[list]                 # empty when is_large_result = True
    chunks_used: list[str]
    chunks_detail: list[ChunkDetail]
    rationale: str
    attempts: int
    fix_history: list[dict]
    total_count: int                 # row count (exact for small; lower bound for large)
    is_large_result: bool            # True → frontend must paginate via /api/paginate
    sql_for_pagination: str          # base SQL without LIMIT/OFFSET for safe pagination


class PaginateRequest(BaseModel):
    sql: str          # base SQL (without LIMIT/OFFSET) generated by /api/query
    offset: int = 0
    limit: int = 100


class PaginateResponse(BaseModel):
    columns: list[str]
    column_types: list[str]
    rows: list[list]


# ── Helpers ──────────────────────────────────────────────────────────────────

def embed(text: str) -> list[float]:
    resp = oai.embeddings.create(model="text-embedding-3-small", input=text)
    return resp.data[0].embedding


def retrieve_chunks(question_embedding: list[float], k: int = TOP_K) -> list[dict]:
    vec_str = "[" + ",".join(str(x) for x in question_embedding) + "]"
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    cur.execute(
        """
        SELECT chunk_key, chunk_text,
               1 - (embedding <=> %s::vector) AS similarity
        FROM planning.schema_embeddings
        ORDER BY embedding <=> %s::vector
        LIMIT %s
        """,
        (vec_str, vec_str, k),
    )
    rows = cur.fetchall()
    cur.close()
    conn.close()
    return [dict(r) for r in rows]


def build_prompt(question: str, chunks: list[dict]) -> str:
    context = "\n\n---\n\n".join(c["chunk_text"] for c in chunks)
    return f"""You are an expert SQL generator for a beverage-company planning database.
Use ONLY the schema context provided below (retrieved via RAG) to write a correct PostgreSQL query.

RULES:
- Always prefix every table with the 'planning.' schema.
- Never query the public schema.
- Return ONLY the raw SQL statement – no markdown fences, no explanation.
- Always use explicit JOINs (never implicit comma joins).
- When the user asks about 'sales' without specifying a scenario, use scenario code 'ACTUAL'.
- Limit result rows to {MAX_ROWS} using LIMIT if the query could return many rows.
- Use SUM(f.value) for aggregation on fact_planning.
- Always alias aggregated columns clearly (e.g. AS total_sales).
- HIERARCHY RULE — fact_planning ALWAYS links to LEAF nodes only (is_leaf=TRUE).
  ALL dimension and attribute tables have parent-child hierarchies via parent_id.
  Querying by a NON-LEAF parent ALWAYS requires a double (or triple) join on the same table.
  The specific rules per table:

  REGION (3 levels: United States → Northeast/West/Midwest/South → States):
    Bridge map_customer_region links to LEAF states only.
    For parent region (Northeast etc.):
      JOIN attr_customer_region state_region ON mcr.region_attr_id = state_region.region_attr_id
      JOIN attr_customer_region region_parent ON state_region.parent_id = region_parent.region_attr_id
      WHERE region_parent.name = 'Northeast'

  CHANNEL (3 levels: All → On-Premise/Off-Premise/E-Commerce → leaf channels):
    Bridge map_customer_channel links to LEAF channels only (Bars, Grocery, etc.).
    For parent channel (Off-Premise etc.):
      JOIN attr_customer_channel leaf_ch   ON mcc.channel_attr_id = leaf_ch.channel_attr_id
      JOIN attr_customer_channel parent_ch ON leaf_ch.parent_id   = parent_ch.channel_attr_id
      WHERE parent_ch.name = 'Off-Premise'

  INDUSTRY (2 levels: All → leaf industries): All named industries ARE leaves — direct filter ok.

  PRODUCT (3 levels: Category → Brand → SKU):
    fact_planning links to SKU leaves only. Beer/Wine/Spirits are categories (NOT leaves).
    For category (Beer): triple-join dim_product three times (dpr, dpr_brand, dpr_cat)
    For brand: double-join dim_product (dpr, dpr_brand)
    NEVER filter dim_product.name = 'Beer' without hierarchy joins.

  CUSTOMER (3 levels: Group → Distributor → Individual):
    fact_planning links to individual customer leaves only.
    For group: triple-join dim_customer (dc, dc_dist, dc_grp)
    For distributor: double-join dim_customer (dc, dc_dist)

  ACCOUNT (2 levels: REV/COGS/OPEX → leaf accounts):
    fact_planning links to LEAF accounts only (REV_GROSS, COGS_MAT, etc.).
    CRITICAL — distinguish intent carefully:
      "Gross Sales" or "gross revenue"     → WHERE da.code = 'REV_GROSS'  (1 account)
      "Net Sales" or "net revenue"         → WHERE da.code = 'REV_NET'    (1 account)
      "Discounts"                          → WHERE da.code = 'REV_DISC'   (1 account)
      "Sales" with NO qualifier (default)  → WHERE da.code = 'REV_GROSS'  (1 account)
      *** "TOTAL REVENUE" / "all revenue" / "revenue by month/industry/channel" /
          "all revenue accounts" / "all children of revenue" / "revenue breakdown" ***
          → MUST use double-join: WHERE da_parent.code = 'REV'
          → TWO sub-cases:
            a) "BREAKDOWN / each account / per account": include da.name in SELECT + GROUP BY
               → produces 3 rows per period (Gross Sales, Discounts, Net Sales)
            b) "SUM / total / combined / aggregate / sum of all children":
               DO NOT include da.name in SELECT or GROUP BY at all
               → collapses all 3 children into ONE number per period/industry/etc.
               Example: "sum of all children of revenue by month by industry"
               → SELECT dp.month_name, aci.name, SUM(f.value) AS total_revenue
                  ... WHERE da_parent.code = 'REV'
                  GROUP BY dp.period_sort, dp.month_name, aci.name
          DO NOT use da.code = 'REV_GROSS' when user says "total revenue" — that is WRONG.
      "Total COGS" / "all COGS" / "cost of goods" → double-join, da_parent.code = 'COGS'
      "Operating expenses" / "all OPEX"            → double-join, da_parent.code = 'OPEX'
    da.code = 'REV', 'COGS', 'OPEX' NEVER exist as leaf codes — these are group nodes.

  PACKAGING (3 levels: All → Bottle/Can/Keg/Box → leaves):
    Bridge map_product_packaging links to leaves only.
    For parent packaging (Bottle etc.): double-join attr_product_packaging.

  PROCESS (3 levels: All → Distilled/Fermented/Blended → leaves):
    Bridge map_product_process links to leaves only.
    For parent process (Distilled etc.): double-join attr_product_process.

  CASE SIZE (3 levels: All → Packs/Bottle Case → leaves):
    Bridge map_product_case_size links to leaves only.
    For parent case size (Packs etc.): double-join attr_product_case_size.
    CRITICAL — There is NO 'case_size_qty' or 'qty' column in attr_product_case_size.
    Filter ONLY by name or code. Mapping for common user phrases:
      "6-pack" / "case qty = 6"     → WHERE cs.name = '6-pack'   (code = 'CS_PACK_6')
      "12-pack" / "case qty = 12"   → WHERE cs.name = '12-pack'  (code = 'CS_PACK_12')
      "24-pack" / "case qty = 24"   → WHERE cs.name = '24-pack'  (code = 'CS_PACK_24')
      "6 x 750ml" / "6 bottle case" → WHERE cs.name = '6 x 750ml' (code = 'CS_BTL_6X750')
      "12 x 750ml"                  → WHERE cs.name = '12 x 750ml' (code = 'CS_BTL_12X750')
      "24 x 355ml"                  → WHERE cs.name = '24 x 355ml' (code = 'CS_BTL_24X355')
    NOTE: 'cs' alias refers to attr_product_case_size leaf join. Always set is_leaf = TRUE for direct leaf filter.

  GAAP/CASHFLOW (2 levels): All named categories ARE leaves — direct filter ok.

- NO RECURSIVE CTEs: NEVER use WITH RECURSIVE in any query. The database does not support it.
  Always use the double/triple-join approach for parent-child hierarchy traversal.
- NEVER combine a parent node name filter AND is_leaf = TRUE — parents are NOT leaves.
- To list CHILDREN of a parent: GROUP BY the leaf alias column (not the parent alias).


SCHEMA CONTEXT (retrieved chunks):
{context}

USER QUESTION:
{question}

SQL:"""


def extract_sql(raw: str) -> str:
    raw = raw.strip()
    raw = re.sub(r"^```[a-z]*\n?", "", raw, flags=re.IGNORECASE)
    raw = re.sub(r"\n?```$", "", raw, flags=re.IGNORECASE)
    return raw.strip()


def strip_limit_offset(sql: str) -> str:
    """Remove trailing LIMIT / OFFSET from the outermost SELECT statement."""
    sql = sql.strip().rstrip(";")
    # Strip LIMIT N [OFFSET M] or OFFSET M [LIMIT N] at the very end
    sql = re.sub(r"\s+LIMIT\s+\d+\s*$", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\s+OFFSET\s+\d+\s*$", "", sql, flags=re.IGNORECASE)
    return sql.strip()


def _col_type(type_code: int) -> str:
    return "numeric" if type_code in NUMERIC_OIDS else "text"


def probe_columns(base_sql: str) -> tuple[list[str], list[str]]:
    """
    Run 'SELECT * FROM (base_sql) LIMIT 0' to validate SQL and return
    column names + types without transferring any row data.
    """
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM ({base_sql}) AS _probe LIMIT 0")
    columns   = [desc[0]              for desc in cur.description]
    col_types = [_col_type(desc.type_code) for desc in cur.description]
    cur.close()
    conn.close()
    return columns, col_types


def run_query(sql: str) -> tuple[list[str], list[list], list[str]]:
    """Execute SQL; return (column_names, rows_as_strings, column_types)."""
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor()
    cur.execute(sql)
    columns   = [desc[0]                   for desc in cur.description]
    col_types = [_col_type(desc.type_code) for desc in cur.description]
    rows = cur.fetchall()
    cur.close()
    conn.close()
    serialised = [[str(v) if v is not None else None for v in row] for row in rows]
    return columns, serialised, col_types


def generate_rationale(question: str, chunks: list[dict]) -> str:
    chunk_list = "\n".join(
        f"  {i+1}. \"{c['chunk_key']}\" (similarity {c['similarity']:.3f}) — {c['chunk_text'][:120].strip()}..."
        for i, c in enumerate(chunks)
    )
    prompt = f"""A user asked: "{question}"

To answer this, a RAG system retrieved the following {len(chunks)} schema chunks from a vector database
(ranked by cosine similarity to the embedded question):

{chunk_list}

In 3-5 sentences, explain in plain English:
1. Why these particular chunks were the most relevant to the question.
2. What role each chunk plays in helping the SQL generator answer the question correctly.
Be specific about the chunk names."""

    resp = oai.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
        max_tokens=350,
    )
    return (resp.choices[0].message.content or "").strip()


def build_fix_prompt(question: str, bad_sql: str, error: str, schema_context: str) -> str:
    return f"""You are an expert PostgreSQL query fixer.
The following SQL query failed with a database error. Fix it so it executes correctly.

RULES:
- Return ONLY the corrected raw SQL statement — no markdown fences, no explanation.
- Do NOT change the intent of the query; only fix the syntax/logic error.
- Always prefix every table with the 'planning.' schema.
- NEVER use WITH RECURSIVE or any recursive CTE — the database does not support it.
  For region hierarchy queries, always use the double-join pattern:
    JOIN planning.attr_customer_region state_region ON mcr.region_attr_id = state_region.region_attr_id
    JOIN planning.attr_customer_region region_parent ON state_region.parent_id = region_parent.region_attr_id
- CASE SIZE: The table attr_product_case_size has NO 'case_size_qty' or 'qty' column.
  Filter by name only: '6-pack' (CS_PACK_6), '12-pack' (CS_PACK_12), '24-pack' (CS_PACK_24),
  '6 x 750ml' (CS_BTL_6X750), '12 x 750ml' (CS_BTL_12X750), '24 x 355ml' (CS_BTL_24X355).
  If you see 'case_size_qty' in the failed SQL, replace with: WHERE cs.name = '6-pack' (or appropriate name).

ORIGINAL QUESTION:
{question}

FAILED SQL:
{bad_sql}

POSTGRES ERROR:
{error}

SCHEMA CONTEXT (for reference):
{schema_context}

FIXED SQL:"""


# ── Endpoints ────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/api/query", response_model=QueryResponse)
def query(req: QueryRequest):
    if not req.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    # ── Step 1: Embed question ───────────────────────────────────────────────
    q_embedding = embed(req.question)

    # ── Step 2: Retrieve schema chunks ──────────────────────────────────────
    chunks = retrieve_chunks(q_embedding)
    chunks_used = [c["chunk_key"] for c in chunks]

    # ── Step 3: Build RAG prompt ─────────────────────────────────────────────
    prompt = build_prompt(req.question, chunks)

    # ── Step 4: Generate SQL with GPT-4o ─────────────────────────────────────
    completion = oai.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )
    raw_sql = completion.choices[0].message.content or ""
    sql = extract_sql(raw_sql)

    # ── Step 5: Generate rationale in parallel (uses fast gpt-4o-mini) ───────
    rationale = generate_rationale(req.question, chunks)

    # ── Step 6: Build rich chunk details for the UI ──────────────────────────
    chunks_detail = [
        ChunkDetail(
            key=c["chunk_key"],
            similarity=round(float(c["similarity"]), 4),
            excerpt=c["chunk_text"][:150].strip() + ("…" if len(c["chunk_text"]) > 150 else ""),
            full_text=c["chunk_text"],
        )
        for c in chunks
    ]

    schema_context = "\n\n---\n\n".join(c["chunk_text"] for c in chunks)

    # ── Step 7: Validate SQL + auto-fix retry loop ───────────────────────────
    # We use a LIMIT 0 probe for validation — no row data is transferred,
    # just enough to confirm the SQL is syntactically and semantically valid
    # and to capture column names / types.
    base_sql   = strip_limit_offset(sql)
    fix_history: list[dict] = []
    columns:    list[str]   = []
    col_types:  list[str]   = []
    attempt = 0

    for attempt in range(1, MAX_SQL_RETRIES + 1):
        try:
            columns, col_types = probe_columns(base_sql)
            break  # SQL is valid
        except Exception as exc:
            error_msg = str(exc)
            fix_history.append({"attempt": attempt, "error": error_msg, "sql": sql})

            if attempt == MAX_SQL_RETRIES:
                raise HTTPException(
                    status_code=422,
                    detail=(
                        f"SQL failed after {MAX_SQL_RETRIES} attempts.\n\n"
                        f"Last error: {error_msg}\n\n"
                        f"Last SQL:\n{sql}"
                    ),
                )

            fix_completion = oai.chat.completions.create(
                model="gpt-4o",
                messages=[{
                    "role": "user",
                    "content": build_fix_prompt(req.question, sql, error_msg, schema_context),
                }],
                temperature=0,
            )
            sql      = extract_sql(fix_completion.choices[0].message.content or "")
            base_sql = strip_limit_offset(sql)

    # ── Step 8: Decide client-side vs server-side pagination ─────────────────
    # Fetch LARGE_RESULT_THRESHOLD + 1 rows.
    # If we get ≤ threshold rows → small result: return all data (client-side).
    # If we get threshold + 1 rows → large result: return no data and let the
    #   frontend paginate via /api/paginate (server-side / Infinite Row Model).
    fetch_sql = (
        f"SELECT * FROM ({base_sql}) AS _fetch "
        f"LIMIT {LARGE_RESULT_THRESHOLD + 1}"
    )
    _, fetched_rows, _ = run_query(fetch_sql)

    if len(fetched_rows) <= LARGE_RESULT_THRESHOLD:
        return QueryResponse(
            sql=sql,
            columns=columns,
            column_types=col_types,
            rows=fetched_rows,
            chunks_used=chunks_used,
            chunks_detail=chunks_detail,
            rationale=rationale,
            attempts=attempt,
            fix_history=fix_history,
            total_count=len(fetched_rows),
            is_large_result=False,
            sql_for_pagination=base_sql,
        )
    else:
        # Large result — rows intentionally empty; frontend will paginate
        return QueryResponse(
            sql=sql,
            columns=columns,
            column_types=col_types,
            rows=[],
            chunks_used=chunks_used,
            chunks_detail=chunks_detail,
            rationale=rationale,
            attempts=attempt,
            fix_history=fix_history,
            total_count=LARGE_RESULT_THRESHOLD,  # lower bound (exact count not fetched)
            is_large_result=True,
            sql_for_pagination=base_sql,
        )


# ── Grid-config response models ──────────────────────────────────────────────

class GridDefinitionOut(BaseModel):
    grid_id:            int
    grid_name:          str
    description:        str | None
    dataset_table:      str | None
    pagination_enabled: bool
    page_size:          int
    frozen_columns:     int
    frozen_rows:        int
    allow_export:       bool
    allow_edit:         bool
    primary_key_field:  str         # PK column name derived from information_schema


class GridColumnOut(BaseModel):
    column_id:    int
    field_name:   str
    header_name:  str | None
    data_type:    str | None
    sortable:     bool
    filterable:   bool
    editable:     bool
    visible:      bool
    pinned:       str | None
    column_order: int | None
    can_view:     bool
    can_edit:     bool


class GridFormatRuleOut(BaseModel):
    field_name:           str
    condition_expression: str | None
    style_json:           dict
    priority:             int


class GridConfigResponse(BaseModel):
    grid:         GridDefinitionOut
    columns:      list[GridColumnOut]
    format_rules: list[GridFormatRuleOut]


class EmployeesResponse(BaseModel):
    columns:      list[str]
    column_types: list[str]
    rows:         list[list]


# ── Employee bulk-update models ───────────────────────────────────────────────

class BulkUpdateItem(BaseModel):
    id:      int
    changes: dict[str, object]   # field_name → new value


class BulkUpdateRequest(BaseModel):
    updates: list[BulkUpdateItem]


class BulkUpdateResponse(BaseModel):
    updated_rows: int
    errors:       list[str]


@app.patch("/api/employees", response_model=BulkUpdateResponse)
def bulk_update_employees(req: BulkUpdateRequest):
    """
    Write pending cell edits back to planning.employees.
    Only fields marked editable=TRUE in planning.grid_columns are accepted.
    """
    if not req.updates:
        return BulkUpdateResponse(updated_rows=0, errors=[])

    conn = psycopg2.connect(DB_URL)
    cur  = conn.cursor()
    try:
        # Fetch the allowlist of editable field names from the grid config
        cur.execute("""
            SELECT gc.field_name
            FROM   planning.grid_columns gc
            JOIN   planning.grid_definitions gd ON gd.grid_id = gc.grid_id
            WHERE  gd.grid_name = 'Employees'
              AND  gc.editable  = TRUE
        """)
        editable_fields: set[str] = {row[0] for row in cur.fetchall()}

        updated_rows = 0
        errors: list[str] = []

        for item in req.updates:
            valid = {k: v for k, v in item.changes.items() if k in editable_fields}
            if not valid:
                errors.append(f"Row id={item.id}: no editable fields supplied (got: {list(item.changes.keys())})")
                continue

            set_clause = ", ".join(f'"{k}" = %s' for k in valid)
            values     = list(valid.values()) + [item.id]
            cur.execute(
                f'UPDATE planning.employees SET {set_clause} WHERE id = %s',
                values,
            )
            updated_rows += cur.rowcount

        conn.commit()
        return BulkUpdateResponse(updated_rows=updated_rows, errors=errors)

    except Exception as exc:
        conn.rollback()
        raise HTTPException(status_code=500, detail=str(exc))
    finally:
        cur.close()
        conn.close()


@app.get("/api/employees", response_model=EmployeesResponse)
def get_employees():
    """Return all rows from planning.employees."""
    try:
        columns, rows, col_types = run_query("SELECT * FROM planning.employees ORDER BY 1")
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))
    return EmployeesResponse(columns=columns, column_types=col_types, rows=rows)


@app.get("/api/grid-config", response_model=GridConfigResponse)
def get_grid_config(grid_name: str = "Employees", role: str = "viewer"):
    """
    Return the merged grid configuration for a given grid name and role.
    Runs 3 queries:
      1. grid_definitions LEFT JOIN grid_role_layout  (role-aware layout)
      2. grid_columns      LEFT JOIN grid_column_permissions (role-aware column access)
      3. grid_format_rules JOIN grid_columns           (conditional cell styles)
    """
    conn = psycopg2.connect(DB_URL)
    cur  = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)

    try:
        # ── Query 1: grid + role layout + primary-key field ──────────────────
        # The PK column name is looked up from information_schema so that the
        # frontend can identify each row generically (e.g. "id" for employees,
        # "contact_id" for contacts) without any hardcoded assumptions.
        cur.execute("""
            SELECT
                gd.grid_id,
                gd.grid_name,
                gd.description,
                gd.dataset_table,
                gd.pagination_enabled,
                COALESCE(grl.page_size,      gd.page_size)      AS page_size,
                COALESCE(grl.frozen_columns, gd.frozen_columns) AS frozen_columns,
                gd.frozen_rows,
                COALESCE(grl.allow_export, TRUE)                AS allow_export,
                COALESCE(grl.allow_edit,   FALSE)               AS allow_edit,
                COALESCE(kcu.column_name,  'id')                AS primary_key_field
            FROM  planning.grid_definitions  gd
            LEFT JOIN planning.grid_role_layout grl
                   ON  grl.grid_id   = gd.grid_id
                   AND grl.role_name = %s
            -- Derive the PK column name from information_schema (first ordinal position)
            LEFT JOIN information_schema.table_constraints tc
                   ON  tc.table_schema     = 'planning'
                   AND tc.table_name       = SPLIT_PART(COALESCE(gd.dataset_table, ''), '.', 2)
                   AND tc.constraint_type  = 'PRIMARY KEY'
            LEFT JOIN information_schema.key_column_usage kcu
                   ON  kcu.constraint_name = tc.constraint_name
                   AND kcu.table_schema    = tc.table_schema
                   AND kcu.ordinal_position = 1
            WHERE gd.grid_name = %s
        """, (role, grid_name))
        grid_row = cur.fetchone()
        if not grid_row:
            raise HTTPException(status_code=404, detail=f"Grid '{grid_name}' not found.")
        grid_id = grid_row["grid_id"]

        # ── Query 2: columns + role permissions ──────────────────────────────
        cur.execute("""
            SELECT
                gc.column_id,
                gc.field_name,
                gc.header_name,
                gc.data_type,
                gc.sortable,
                gc.filterable,
                gc.editable,
                gc.visible,
                gc.pinned,
                gc.column_order,
                COALESCE(gcp.can_view, TRUE)  AS can_view,
                COALESCE(gcp.can_edit, FALSE) AS can_edit
            FROM  planning.grid_columns gc
            LEFT JOIN planning.grid_column_permissions gcp
                   ON  gcp.column_id  = gc.column_id
                   AND gcp.role_name  = %s
            WHERE gc.grid_id = %s
            ORDER BY gc.column_order
        """, (role, grid_id))
        col_rows = cur.fetchall()

        # ── Query 3: format rules ─────────────────────────────────────────────
        cur.execute("""
            SELECT
                gc.field_name,
                gfr.condition_expression,
                gfr.style_json,
                gfr.priority
            FROM  planning.grid_format_rules gfr
            JOIN  planning.grid_columns gc
                   ON gc.column_id = gfr.column_id
            WHERE gc.grid_id = %s
            ORDER BY gc.field_name, gfr.priority ASC
        """, (grid_id,))
        rule_rows = cur.fetchall()

    finally:
        cur.close()
        conn.close()

    return GridConfigResponse(
        grid=GridDefinitionOut(**dict(grid_row)),
        columns=[GridColumnOut(**dict(r)) for r in col_rows],
        format_rules=[
            GridFormatRuleOut(
                field_name=r["field_name"],
                condition_expression=r["condition_expression"],
                style_json=dict(r["style_json"]) if r["style_json"] else {},
                priority=r["priority"],
            )
            for r in rule_rows
        ],
    )


# ── Generic grid-data endpoints (work for ANY grid in grid_definitions) ──────

@app.get("/api/grid-data", response_model=EmployeesResponse)
def get_grid_data(grid_name: str = "Employees"):
    """
    Return all rows from the dataset_table configured for the given grid.
    Looks up planning.grid_definitions.dataset_table, then runs
      SELECT * FROM <dataset_table> ORDER BY 1
    Supports any grid (Employees, Contacts, or any future grid) — no
    per-table endpoint needed.
    """
    conn = psycopg2.connect(DB_URL)
    cur  = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cur.execute(
            "SELECT dataset_table FROM planning.grid_definitions WHERE grid_name = %s",
            (grid_name,)
        )
        row = cur.fetchone()
    finally:
        cur.close()
        conn.close()

    if not row:
        raise HTTPException(status_code=404, detail=f"Grid '{grid_name}' not found.")
    dataset_table = row["dataset_table"]
    if not dataset_table:
        raise HTTPException(status_code=400, detail=f"Grid '{grid_name}' has no dataset_table configured.")
    if not dataset_table.startswith("planning."):
        raise HTTPException(status_code=400, detail="Only planning.* tables are supported.")

    try:
        columns, rows, col_types = run_query(f"SELECT * FROM {dataset_table} ORDER BY 1")
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))

    return EmployeesResponse(columns=columns, column_types=col_types, rows=rows)


@app.patch("/api/grid-data", response_model=BulkUpdateResponse)
def bulk_update_grid_data(grid_name: str, req: BulkUpdateRequest):
    """
    Write pending cell edits back to the dataset_table for the given grid.
    - Looks up the editable columns from planning.grid_columns.
    - Looks up the PK column name from information_schema.
    - Only fields marked editable=TRUE are accepted (SQL-injection-safe allowlist).
    Works for any grid (Employees, Contacts, etc.) without per-table code.
    """
    if not req.updates:
        return BulkUpdateResponse(updated_rows=0, errors=[])

    conn = psycopg2.connect(DB_URL)
    cur  = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        # ── Look up dataset_table + editable columns ──────────────────────────
        cur.execute("""
            SELECT gd.dataset_table, gc.field_name
            FROM   planning.grid_definitions gd
            JOIN   planning.grid_columns gc ON gc.grid_id = gd.grid_id
            WHERE  gd.grid_name  = %s
              AND  gc.editable   = TRUE
        """, (grid_name,))
        results = cur.fetchall()
        if not results:
            raise HTTPException(
                status_code=404,
                detail=f"Grid '{grid_name}' not found or has no editable columns."
            )

        dataset_table    = results[0]["dataset_table"]
        editable_fields  = {r["field_name"] for r in results}

        if not dataset_table:
            raise HTTPException(status_code=400, detail=f"Grid '{grid_name}' has no dataset_table configured.")
        if not dataset_table.startswith("planning."):
            raise HTTPException(status_code=400, detail="Only planning.* tables are supported.")

        # ── Look up the actual primary-key column name ────────────────────────
        table_name = dataset_table.split(".", 1)[1]   # e.g. "employees" or "contacts"
        cur.execute("""
            SELECT kcu.column_name
            FROM   information_schema.table_constraints tc
            JOIN   information_schema.key_column_usage kcu
                   ON  kcu.constraint_name  = tc.constraint_name
                   AND kcu.table_schema     = tc.table_schema
            WHERE  tc.table_schema      = 'planning'
              AND  tc.table_name        = %s
              AND  tc.constraint_type   = 'PRIMARY KEY'
            ORDER  BY kcu.ordinal_position
            LIMIT  1
        """, (table_name,))
        pk_row = cur.fetchone()
        pk_col = pk_row["column_name"] if pk_row else "id"

        # ── Apply updates ─────────────────────────────────────────────────────
        # Switch to regular cursor for DML (RealDictCursor not needed)
        cur.close()
        cur = conn.cursor()

        updated_rows = 0
        errors: list[str] = []

        for item in req.updates:
            valid = {k: v for k, v in item.changes.items() if k in editable_fields}
            if not valid:
                errors.append(
                    f"Row pk={item.id}: no editable fields supplied "
                    f"(got: {list(item.changes.keys())})"
                )
                continue

            set_clause = ", ".join(f'"{k}" = %s' for k in valid)
            values     = list(valid.values()) + [item.id]
            cur.execute(
                f'UPDATE {dataset_table} SET {set_clause} WHERE "{pk_col}" = %s',
                values,
            )
            updated_rows += cur.rowcount

        conn.commit()
        return BulkUpdateResponse(updated_rows=updated_rows, errors=errors)

    except HTTPException:
        raise
    except Exception as exc:
        conn.rollback()
        raise HTTPException(status_code=500, detail=str(exc))
    finally:
        cur.close()
        conn.close()


@app.post("/api/paginate", response_model=PaginateResponse)
def paginate(req: PaginateRequest):
    """
    Execute a pre-validated base SQL query with LIMIT / OFFSET for server-side
    pagination.  Only called by the frontend when is_large_result = True.
    """
    clean = req.sql.strip()

    # Basic security: must be a read-only SELECT or WITH (CTE) query
    if not re.match(r"^\s*(SELECT|WITH)\b", clean, re.IGNORECASE):
        raise HTTPException(status_code=400, detail="Only SELECT queries are allowed.")
    if _FORBIDDEN_SQL.search(clean):
        raise HTTPException(status_code=400, detail="Forbidden SQL operation detected.")
    if not (1 <= req.limit <= 500):
        raise HTTPException(status_code=400, detail="limit must be between 1 and 500.")
    if req.offset < 0:
        raise HTTPException(status_code=400, detail="offset must be >= 0.")

    paginated_sql = (
        f"SELECT * FROM ({clean}) AS _paged "
        f"LIMIT {req.limit} OFFSET {req.offset}"
    )
    try:
        columns, rows, col_types = run_query(paginated_sql)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))

    return PaginateResponse(columns=columns, column_types=col_types, rows=rows)
